Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> s={a,}
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    s={a,}
NameError: name 'a' is not defined
>>> s={}
>>> ws
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    ws
NameError: name 'ws' is not defined
>>> dic={name:,value:}
SyntaxError: invalid syntax
>>> dic={}
>>> type(dic)
<class 'dict'>
>>> s={}
>>> type(s)
<class 'dict'>
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py", line 3, in <module>
    display(bar)
NameError: name 'display' is not defined
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
sindhu
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
2.8125
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
56
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
13
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
<built-in function sum>
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
<built-in function sum>
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
sum
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
90
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
90
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
23 67
90
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
>>> 6
6
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
34
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/higherarg.py 
114
>>> 
 RESTART: C:\Users\HP\AppData\Local\Programs\Python\Python37-32\prgms\factrec.py 
enter a num5
120
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
9
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
18
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
1
2
3
4
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
1
2
3
4
6
7
8
9
10
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
1
2
3
4
6
7
8
9
10
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
1
2
3
4
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py", line 18, in <module>
    print(username(x))
NameError: name 'x' is not defined
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
enter username:abc
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py", line 18, in <module>
    print(username())
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py", line 15, in username
    password()
NameError: name 'password' is not defined
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
enter username:abc
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py", line 18, in <module>
    print(username())
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py", line 15, in username
    password()
NameError: name 'password' is not defined
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
enter username:abc
enter password:xyz
login successfully
None
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
enter username:abc
enter password:xyz
login successfully
>>> 
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
enter username:sindhu
enter username:vgjvg
enter username:vhivh
enter username:vhivh
enter username:
= RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/anonymus.py =
enter username:hcgc
enter username:ctuctu
enter username:cugc
enter username:abc
enter password:dtd
enter password:dyd
enter password:dyu
enter password:tutu
enter password:ftuyu
enter password:xyz
login successfully
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 1, in <module>
    list=[(sindhu,ece,20),(sanju,cse,21),(bhav,mech,32)]
NameError: name 'sindhu' is not defined
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 2, in <module>
    print(convert(list,dictionary))
NameError: name 'convert' is not defined
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 3, in <module>
    print(convert(list,dictionary))
NameError: name 'convert' is not defined
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 3, in <module>
    print (convert(list,dictionary))
NameError: name 'convert' is not defined
>>> list=["hnjh",78]
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 3, in <module>
    print(extend(list,dictionary))
NameError: name 'extend' is not defined
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 6, in <module>
    print(convert(list,dictionary))
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 2, in convert
    dic=dict(list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
{'sindhu': 'ece', 'sanju': 'cse', 'bhav': 'mech'}
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 6, in <module>
    print(convert(list,dictionary))
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 2, in convert
    dic=dict(list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 5, in <module>
    print(convert(list,dictionary))
NameError: name 'dictionary' is not defined
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
{'sindhu': 'ece', 'sanju': 'cse', 'bhav': 'mech'}
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 6, in <module>
    print(convert(list,dictionary))
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 2, in convert
    dic=dict(list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
{'sindhu': 'ece', 'sanju': 'cse', 'bhav': 'mech'}
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 6, in <module>
    print(convert(list,dictionary))
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py", line 2, in convert
    dic=dict(list)
ValueError: dictionary update sequence element #0 has length 3; 2 is required
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
{'sindhu': 'ece\n13', 'sanju': 'cse\n 14', 'bhav': 'mech\n 55'}
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
{'sindhu': 'ece\n  13', 'sanju': 'cse\n 14', 'bhav': 'mech\n 55'}
>>> 
 RESTART: C:/Users/HP/AppData/Local/Programs/Python/Python37-32/prgms/listtodic.py 
{'sindhu': 'ece:13', 'sanju': 'cse:14', 'bhav': 'mech:55'}
>>> x="ghbjk"
>>> x.case fold()
SyntaxError: invalid syntax
>>> x.casefold()
'ghbjk'
>>> x.casefold(b)
Traceback (most recent call last):
  File "<pyshell#13>", line 1, in <module>
    x.casefold(b)
NameError: name 'b' is not defined
>>> x="gYTHNMKk"
>>> x.casefold()
'gythnmkk'
>>> x.center(5,tvg)
Traceback (most recent call last):
  File "<pyshell#16>", line 1, in <module>
    x.center(5,tvg)
NameError: name 'tvg' is not defined
>>> x.center(5)
'gYTHNMKk'
>>> x.center(5,"jhni")
Traceback (most recent call last):
  File "<pyshell#18>", line 1, in <module>
    x.center(5,"jhni")
TypeError: The fill character must be exactly one character long
>>> x.center(5,' ')
'gYTHNMKk'
>>> x.center(6,' ')
'gYTHNMKk'
>>> x.center(6,'h')
'gYTHNMKk'
>>> x.center(20,'h')
'hhhhhhgYTHNMKkhhhhhh'
>>> x.count(g)
Traceback (most recent call last):
  File "<pyshell#23>", line 1, in <module>
    x.count(g)
NameError: name 'g' is not defined
>>> x.count("g")
1
>>> x.encode()
b'gYTHNMKk'
>>> x.expandtabs()
'gYTHNMKk'
>>> x.expandtabs(6)
'gYTHNMKk'
>>> x.expandtabs(20)
'gYTHNMKk'
>>> x.expandtabs(20,"N")
Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    x.expandtabs(20,"N")
TypeError: expandtabs() takes at most 1 argument (2 given)
>>> x.expandtabs("N")
Traceback (most recent call last):
  File "<pyshell#30>", line 1, in <module>
    x.expandtabs("N")
TypeError: an integer is required (got type str)
>>> x.expandtabs(20)
'gYTHNMKk'
>>> x="ghbj\nk"
>>> x.expandtabs(20)
'ghbj\nk'
>>> x="ghbj\tk"
>>> x.expandtabs(20)
'ghbj                k'
>>> x.find(g)
Traceback (most recent call last):
  File "<pyshell#36>", line 1, in <module>
    x.find(g)
NameError: name 'g' is not defined
>>> x.find("g")
0
>>> x.find("b")
2
>>> x.format()
'ghbj\tk'
>>> x.format("b")
'ghbj\tk'
>>> x="ghbjtk"
>>> x.format("b")
'ghbjtk'
>>> x="ghbjtk{}"
>>> x.format("b")
'ghbjtkb'
>>> x.format_map("b")
Traceback (most recent call last):
  File "<pyshell#45>", line 1, in <module>
    x.format_map("b")
ValueError: Format string contains positional fields
>>> x="kjmlmo"
>>> x.format_map("b","h")
Traceback (most recent call last):
  File "<pyshell#47>", line 1, in <module>
    x.format_map("b","h")
TypeError: format_map() takes exactly one argument (2 given)
>>> x="kjm{}lm{}o"
>>> x.format_map("b","h")
Traceback (most recent call last):
  File "<pyshell#49>", line 1, in <module>
    x.format_map("b","h")
TypeError: format_map() takes exactly one argument (2 given)
>>> x.format_map("b")
Traceback (most recent call last):
  File "<pyshell#50>", line 1, in <module>
    x.format_map("b")
ValueError: Format string contains positional fields
>>> x.format_map(6)
Traceback (most recent call last):
  File "<pyshell#51>", line 1, in <module>
    x.format_map(6)
ValueError: Format string contains positional fields
>>> x.format_map(b,h)
Traceback (most recent call last):
  File "<pyshell#52>", line 1, in <module>
    x.format_map(b,h)
NameError: name 'b' is not defined
>>> x.index(3)
Traceback (most recent call last):
  File "<pyshell#53>", line 1, in <module>
    x.index(3)
TypeError: must be str, not int
>>> x.index("j")
1
>>> x.isalnum()
False
>>> x.isidentifier()
False
>>> x.iskeyword()
Traceback (most recent call last):
  File "<pyshell#57>", line 1, in <module>
    x.iskeyword()
AttributeError: 'str' object has no attribute 'iskeyword'
>>> x.iskeyword("j")
Traceback (most recent call last):
  File "<pyshell#58>", line 1, in <module>
    x.iskeyword("j")
AttributeError: 'str' object has no attribute 'iskeyword'
>>> x.iskeyword(class)
SyntaxError: invalid syntax
>>> x.iskeyword("class")
Traceback (most recent call last):
  File "<pyshell#60>", line 1, in <module>
    x.iskeyword("class")
AttributeError: 'str' object has no attribute 'iskeyword'
>>> x.join(['jj',['hj']])
Traceback (most recent call last):
  File "<pyshell#61>", line 1, in <module>
    x.join(['jj',['hj']])
TypeError: sequence item 1: expected str instance, list found
>>> x.join(['jj',['hj'])
       
SyntaxError: invalid syntax
>>> x.join(['jj'],['hj'])
Traceback (most recent call last):
  File "<pyshell#63>", line 1, in <module>
    x.join(['jj'],['hj'])
TypeError: join() takes exactly one argument (2 given)
>>> x.join('jj','hj')
Traceback (most recent call last):
  File "<pyshell#64>", line 1, in <module>
    x.join('jj','hj')
TypeError: join() takes exactly one argument (2 given)
>>> y="njnjm"
>>> x.join(y)
'nkjm{}lm{}ojkjm{}lm{}onkjm{}lm{}ojkjm{}lm{}om'
>>> x
'kjm{}lm{}o'
>>> ljust(9,"h")
Traceback (most recent call last):
  File "<pyshell#68>", line 1, in <module>
    ljust(9,"h")
NameError: name 'ljust' is not defined
>>> x.ljust(9,"h")
'kjm{}lm{}o'
>>> y.ljust(9,"h")
'njnjmhhhh'
>>> 
